# bake_credentials.ps1
# Reads .env from the project root and writes the values directly into app.py
# as os.environ defaults, so PyInstaller will bake them into the exe.
#
# Run this BEFORE every PyInstaller build, in the project root:
#   .\bake_credentials.ps1

$ErrorActionPreference = "Stop"

$projectDir = Split-Path -Parent $MyInvocation.MyCommand.Path
Set-Location $projectDir

if (-not (Test-Path ".env")) {
    Write-Host ".env not found in project root" -ForegroundColor Red
    exit 1
}
if (-not (Test-Path "app.py")) {
    Write-Host "app.py not found in project root" -ForegroundColor Red
    exit 1
}

# Parse .env into key=value pairs
$envVars = @{}
Get-Content .env | ForEach-Object {
    $line = $_.Trim()
    if ($line -and -not $line.StartsWith("#")) {
        $parts = $line -split "=", 2
        if ($parts.Count -eq 2) {
            $key = $parts[0].Trim()
            $val = $parts[1].Trim().Trim('"').Trim("'")
            $envVars[$key] = $val
        }
    }
}

Write-Host "Found $($envVars.Count) env variables in .env"

# Build the Python block to inject
$pyLines = @()
$pyLines += "# BAKED_CREDENTIALS_START - auto-generated by bake_credentials.ps1"
$pyLines += "# This block sets defaults for env vars only if they are not already set."
$pyLines += "import os as _os_baked"
foreach ($key in $envVars.Keys) {
    $val = $envVars[$key]
    $escaped = $val.Replace("\", "\\").Replace('"', '\"')
    $pyLines += "_os_baked.environ.setdefault(`"$key`", `"$escaped`")"
}
$pyLines += "# BAKED_CREDENTIALS_END"
$pyLines += ""

$inject = $pyLines -join "`n"

# Read app.py
$content = Get-Content -Raw -Path app.py

# Remove any previous baked block (idempotent re-runs)
# Match from "# BAKED_CREDENTIALS_START" through "# BAKED_CREDENTIALS_END"
# plus any trailing blank lines, anywhere in the file.
$pattern = '(?ms)# BAKED_CREDENTIALS_START.*?# BAKED_CREDENTIALS_END\s*'
$content = [regex]::Replace($content, $pattern, '')

# Inject right at the top, after the docstring if there is one
$tripleQuote = [char]34 + [char]34 + [char]34
$docPattern = '(?s)^(' + [regex]::Escape($tripleQuote) + '[^' + [char]34 + ']*?' + [regex]::Escape($tripleQuote) + ')'
if ($content -match $docPattern) {
    $docstring = $matches[1]
    $rest = $content.Substring($docstring.Length)
    $content = $docstring + "`n`n" + $inject + $rest
} else {
    $content = $inject + $content
}

# Write back as UTF-8 without BOM
$utf8NoBom = New-Object System.Text.UTF8Encoding $false
[System.IO.File]::WriteAllText((Resolve-Path "app.py"), $content, $utf8NoBom)

Write-Host "Credentials baked into app.py" -ForegroundColor Green
Write-Host "Now run:  .\venv\Scripts\python.exe -m PyInstaller --clean Voice2Claude.spec" -ForegroundColor Cyan
