# Voice2Claude - desktop shortcut installer
# Run once. Creates:
#   1. launch.vbs                  (silent wrapper that hides the console window)
#   2. Desktop\Voice2Claude.lnk    -> launch.vbs
#
# Uses python.exe (not pythonw.exe) because pythonw fails silently on some
# Windows configurations. The VBS wrapper hides the console window completely.
#
# Optional: place a 256x256 .ico file at static\app.ico to give the shortcut a
# custom icon. Otherwise the system default icon is used.
#
# Usage from PowerShell, in the project root:
#   .\install_shortcut.ps1

$ErrorActionPreference = "Stop"

$projectDir = Split-Path -Parent $MyInvocation.MyCommand.Path
Set-Location $projectDir

Write-Host "Project directory: $projectDir" -ForegroundColor Cyan

# ----- 1. Sanity check -----
$appPy   = Join-Path $projectDir "app.py"
$venvPy  = Join-Path $projectDir "venv\Scripts\python.exe"
$icoPath = Join-Path $projectDir "static\app.ico"
$vbsPath = Join-Path $projectDir "launch.vbs"

if (-not (Test-Path $appPy))  { Write-Host "Could not find app.py"  -ForegroundColor Red; exit 1 }
if (-not (Test-Path $venvPy)) { Write-Host "Could not find venv\Scripts\python.exe" -ForegroundColor Red; exit 1 }

if (-not (Test-Path $icoPath)) {
    Write-Host "static\app.ico not found - shortcut will use default icon" -ForegroundColor Yellow
    $icoPath = $null
}

# ----- 2. Write the VBScript launcher -----
# This wrapper:
#   - Sets working directory to the project root (so .env loads)
#   - Launches python.exe with WindowStyle 0 = HIDDEN (no visible console)
#   - Does NOT wait for the process to finish — fires and forgets
Write-Host "Writing launch.vbs..." -ForegroundColor Cyan

$projectDirEsc = $projectDir.Replace('"', '""')
$venvPyEsc     = $venvPy.Replace('"', '""')
$appPyEsc      = $appPy.Replace('"', '""')

$vbs = @"
' Voice2Claude launcher - generated by install_shortcut.ps1
' Do not edit; re-run install_shortcut.ps1 to regenerate.

Dim shell
Set shell = CreateObject("WScript.Shell")
shell.CurrentDirectory = "$projectDirEsc"
' WindowStyle 0 = hidden, bWaitOnReturn = False (don't block).
shell.Run """$venvPyEsc"" ""$appPyEsc""", 0, False
"@

Set-Content -Path $vbsPath -Value $vbs -Encoding ASCII
Write-Host "  -> $vbsPath" -ForegroundColor Green

# ----- 3. Create the desktop shortcut pointing to launch.vbs -----
$desktop = [Environment]::GetFolderPath("Desktop")
$lnkPath = Join-Path $desktop "Voice2Claude.lnk"

Write-Host "Creating shortcut $lnkPath..." -ForegroundColor Cyan

$wshShell = New-Object -ComObject WScript.Shell
$lnk = $wshShell.CreateShortcut($lnkPath)
$lnk.TargetPath       = "wscript.exe"
$lnk.Arguments        = """$vbsPath"""
$lnk.WorkingDirectory = $projectDir
$lnk.Description      = "Voice2Claude - local voice conversation app"
$lnk.WindowStyle      = 7  # 7 = minimised
if ($icoPath -and (Test-Path $icoPath)) {
    $lnk.IconLocation = $icoPath
}
$lnk.Save()

Write-Host ""
Write-Host "Done." -ForegroundColor Green
Write-Host "Double-click 'Voice2Claude' on your Desktop to launch." -ForegroundColor Green
